### ISSUE TITLE
Feedback técnico

### ISSUE THREAD

**Issue by RuthSalvador** [BellaAguirre/lim-2018-05-bc-core-am-cipher#1]
# Recomendaciones de mejora 👍

- **`README.md`**: buena idea explicar la funcionalidad del proyecto, además de adicionar tu planificación de estos 2 sprints, imágenes de la evolución de tu producto y producto terminado. Recuerda mencionar la parte UX (tu usuario).

- **`index.html`**: buena validación, sin errores. Te sugerimos utilizar más etiquetas semánticas como `section`, `footer`, etc; evita usar etiquetas como `<br>` para darle estilos, para ello se usa `css`. En cuanto al nombre de tus `id` y `class` puedes usar la sintaxis con guiones normales. 

- **`cipher.js`**: buena lógica para las operaciones de cifrado y descifrado, además de refactorizar tu código, buenazo! Te recomendamos utilizar `forEach` en lugar de `for`, al igual que los métodos de arrays (`ES6)` como `map`, etc. Mejora el nombramientos de tus variables, que sean en inglés y descriptivas.

- **`index.js`**: buena idea declarar al inicio los elementos del DOM que utilizas. Te recomendamos hacer uso de const para las variables offset, string, etc ya que no cambias su valor. Puedes leer un poco más sobre diferencias entre `const` y `let`

- **`style.css`**: recuerda utilizar clases descriptivas y nombralas en inglés; te recomendamos crear clases para reutilizar estilos.

- **Tests**: cumples con las condiciones mínimas de cobertura. Recuerda que si deseas puedes agregar más tests para practicar.

Por último te recomendamos tener en cuenta la guía de estilos y utilizar comillas simples (' ') en archivos `js` y comillas dobles (" ") en el `html`. Además los usuarios deben ver tu producto desde cualquier dispositivo, por lo que te recomendamos realizar tus proyectos responsive (el texto no sea muy pequeño).
Recuerda declarar tus variables, clases, id con nombres en inglés y descriptivas; y cuidar tu indentación la cual debe ser de 2 espacios para todos los archivos.
No te olvides llegar a los niveles esperados en Github.

Sigue así buen trabajo 👍

**Comment by BellaAguirre** [comment]
Gracias por las indicaciones ;)
